/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function bubble_sort_int32array(a: number, b: number): void;
export function bubble_sort_int16array(a: number, b: number): void;
export function bubble_sort_int8array(a: number, b: number): void;
export function bubble_sort_uint32array(a: number, b: number): void;
export function bubble_sort_uint16array(a: number, b: number): void;
export function bubble_sort_uint8array(a: number, b: number): void;
export function bubble_sort_float64array(a: number, b: number): void;
export function bubble_sort_float32array(a: number, b: number): void;
export function insertion_sort_int32array(a: number, b: number): void;
export function insertion_sort_int16array(a: number, b: number): void;
export function insertion_sort_int8array(a: number, b: number): void;
export function insertion_sort_uint32array(a: number, b: number): void;
export function insertion_sort_uint16array(a: number, b: number): void;
export function insertion_sort_uint8array(a: number, b: number): void;
export function insertion_sort_float64array(a: number, b: number): void;
export function insertion_sort_float32array(a: number, b: number): void;
export function heapsort_int32array(a: number, b: number): void;
export function heapsort_int16array(a: number, b: number): void;
export function heapsort_int8array(a: number, b: number): void;
export function heapsort_uint32array(a: number, b: number): void;
export function heapsort_uint16array(a: number, b: number): void;
export function heapsort_uint8array(a: number, b: number): void;
export function heapsort_float64array(a: number, b: number): void;
export function heapsort_float32array(a: number, b: number): void;
export function merge_sort_int32array(a: number, b: number): void;
export function merge_sort_int16array(a: number, b: number): void;
export function merge_sort_int8array(a: number, b: number): void;
export function merge_sort_uint32array(a: number, b: number): void;
export function merge_sort_uint16array(a: number, b: number): void;
export function merge_sort_uint8array(a: number, b: number): void;
export function merge_sort_float64array(a: number, b: number): void;
export function merge_sort_float32array(a: number, b: number): void;
export function selection_sort_int32array(a: number, b: number): void;
export function selection_sort_int16array(a: number, b: number): void;
export function selection_sort_int8array(a: number, b: number): void;
export function selection_sort_uint32array(a: number, b: number): void;
export function selection_sort_uint16array(a: number, b: number): void;
export function selection_sort_uint8array(a: number, b: number): void;
export function selection_sort_float64array(a: number, b: number): void;
export function selection_sort_float32array(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
